export { initVoteEvent } from '@/components/events/posts/init/vote-event'
export { initTimerEvent } from '@/components/events/posts/init/timer-event'
export { initUserEvent } from '@/components/events/posts/init/user-event'
export { initRepostsEvent } from '@/components/events/posts/init/reposts-event'
export { initRankFriendEvent } from '@/components/events/posts/init/rank-friend-event'
export { initStatisticDataEvent } from '@/components/events/posts/init/statistic-data-event'
export { initJudgeRightWrongEvent } from '@/components/events/posts/init/judge-right-wrong-event'
